apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketrush-config
  namespace: ticketrush
data:
  SPRING_PROFILES_ACTIVE: "docker"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "ticketrush"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  QDRANT_URL: "http://qdrant:6333"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_ENABLED: "true"
  OPENROUTER_MODEL: "google/gemini-2.0-flash-exp:free"
  OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1"
  EMBEDDING_MODEL: "text-embedding-3-small"
