apiVersion: v1
kind: Secret
metadata:
  name: ticketrush-secret
  namespace: ticketrush
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  JWT_SECRET: "ticketrush-super-secure-production-jwt-token-key-min-256-bits"
  OPENROUTER_API_KEY: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
